# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160829_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicitem',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
