# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_basicitem_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicitem',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
