# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_content_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='direct_link',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
