# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_direct_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='gallery_object',
            field=models.BooleanField(default=False),
        ),
    ]
