# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_content_gallery_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicitem',
            name='discus_domain',
            field=models.TextField(default=''),
        ),
    ]
