# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_basicitem_discus_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicitem',
            name='accent_color',
            field=models.CharField(choices=[('cyan', 'cyan'), ('light_blue', 'light_blue'), ('blue', 'blue'), ('indigo', 'indigo'), ('deep_purple', 'deep_purple'), ('purple', 'purple'), ('pink', 'pink'), ('red', 'red'), ('deep_orange', 'deep_orange'), ('orange', 'orange'), ('amber', 'amber'), ('yellow', 'yellow'), ('lime', 'lime'), ('light_green', 'light_green'), ('green', 'green'), ('teal', 'teal')], default='teal', max_length=20),
        ),
        migrations.AddField(
            model_name='basicitem',
            name='primary_color',
            field=models.CharField(choices=[('cyan', 'cyan'), ('light_blue', 'light_blue'), ('blue', 'blue'), ('indigo', 'indigo'), ('deep_purple', 'deep_purple'), ('purple', 'purple'), ('pink', 'pink'), ('red', 'red'), ('deep_orange', 'deep_orange'), ('orange', 'orange'), ('amber', 'amber'), ('yellow', 'yellow'), ('lime', 'lime'), ('light_green', 'light_green'), ('green', 'green'), ('teal', 'teal'), ('grey', 'grey'), ('blue_grey', 'blue_grey'), ('brown', 'brown')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='basicitem',
            name='theme_color',
            field=models.CharField(default='#dd1338', max_length=9),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='discus_domain',
            field=models.CharField(default='', max_length=256),
        ),
    ]
