# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160902_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
