# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_content_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicitem',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='discus_domain',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='html_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='html_favicon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='html_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='html_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
